jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest / macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH  # Add to PATH

      - name: Verify Arduino CLI installation
        run: arduino-cli version

      - name: Install ESP32 Board Support
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Libraries
        run: |
          arduino-cli lib install WiFi
          arduino-cli lib install Wire
          arduino-cli lib install math
          arduino-cli lib install "ArduinoOSC"
          arduino-cli lib install "WiFiUdp"

      - name: Compile Code
        run: |
          arduino-cli compile --fqbn esp32:esp32:featheresp32 ./esp32/esp32_accelerometer.ino

      - name: Run Tests
        run: |
          arduino-cli compile --fqbn esp32:esp32:featheresp32 ./esp32/test.ino

      # - name: Upload to ESP32 (Optional, requires USB connection)
      #   run: |
      #     arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:featheresp32 ./path/to/your/arduino_project

